sudo: required
services:
  - docker

before_install:
  - docker build -t mmunson/react-test -f ./DockerAndKubernetes_TheCompleteGuide/complex/client/Dockerfile.dev ./DockerAndKubernetes_TheCompleteGuide/complex/client

script:
  - docker run mmunson/react-test npm test -- --coverage

after_success:
  - docker build -t mmunson/multi-client ./DockerAndKubernetes_TheCompleteGuide/complex/client
  - docker build -t mmunson/multi-nginx ./DockerAndKubernetes_TheCompleteGuide/complex/nginx
  - docker build -t mmunson/multi-server ./DockerAndKubernetes_TheCompleteGuide/complex/server
  - docker build -t mmunson/multi-worker ./DockerAndKubernetes_TheCompleteGuide/complex/worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mmunson/multi-client
  - docker push mmunson/multi-nginx
  - docker push mmunson/multi-server
  - docker push mmunson/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-413030055275
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY