sudo: required
services:
  - docker

before_install:
  - docker build -t mmunson/react-test -f ./complex/client/Dockerfile.dev ./complex/client

script:
  - docker run mmunson/react-test npm test -- --coverage

after_success:
  - docker build -t mmunson/multi-client ./complex/client
  - docker build -t mmunson/multi-nginx ./complex/nginx
  - docker build -t mmunson/multi-server ./complex/server
  - docker build -t mmunson/multi-worker ./complex/worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mmunson/multi-client
  - docker push mmunson/multi-nginx
  - docker push mmunson/multi-server
  - docker push mmunson/multi-worker
